// tienda/React/src/components/Detalle.js
import React from 'react';
import '../css/detalle.css';

class Detalle extends React.Component{
  constructor(props){
      super(props);
      this.state = {
        nombre: this.props.nombre,
        show: true,
        precio: this.props.precio,
        descripcion: this.props.descripcion,
        stock: this.props.stock,
        imagen: this.props.imagen
      }
  }

  hideDetalle() {
    this.setState({
      show: false
    });
    this.props.showCatalogo();
  }

  render(){
    let nombre=this.state.nombre;    
    let descripcion=this.state.descripcion;
    let precio=this.state.precio;
    let stock=this.state.stock;
    let imagen=this.state.imagen;
    let content;

    if (this.state.show) {
      content=<div className="card white"><div className="card-content">
                <span className="card-title gray-text text-lighten-2">{nombre}</span>
                <hr/>
                <div className="row main">
                  <div className="col m5">
                    <img className="img-detalle" src={`../assets/${imagen}`} />
                  </div>
                  <div className="col m7">
                    <dl>
                    <dt>Descrición:</dt>
                      <dd>{descripcion}</dd>
                      <dt>Precio:</dt>
                      <dd>${precio}</dd>
                      <dt>Unidades Disponibles:</dt>
                      <dd>{stock}</dd>
                    </dl>
                    <button onClick={this.hideDetalle.bind(this)} className="btn grey lighten-5 black-text text-darken-2 back-detalle" type="button">Atrás</button>
                  </div>
                </div>
              </div>
            </div>;
    }
    else {
      content=<div></div>;
    }

    return (
      <div>
        {content}
      </div>
    )
  }
}

export default Detalle;

// tienda/Angular/src/app/detalle/detalle.component.ts
import { Component, Input } from '@angular/core';
import { CatalogoComponent } from '../catalogo/catalogo.component';

@Component({
  selector: 'detalle',
  templateUrl: './detalle.component.html',
  styleUrls: ['./detalle.component.css']
})
export class DetalleComponent {
  private show: boolean = false;
  private nombre: string = "";
  private imagen: string = "";
  private precio: string = "";
  private stock: string = "";
  private descripcion: string = "";

  @Input() catalogo: CatalogoComponent;
  showCatalog(){
    this.catalogo.showCatalog();
    this.hideDetails();
  }

  showDetails(nombre, imagen, precio, stock,descripcion){
    this.nombre = nombre;
    this.imagen = imagen;
    this.precio = precio;
    this.stock = stock;
    this.descripcion = descripcion;
    this.show = true;
  }

  hideDetails(){
    this.show = false;
  }
}

<div *ngIf="show" class="card white">
  <div class="card-content">
    <hr>
    <div class="row main">
      <div class="col s12 m12">
        <h2 class="header">{{nombre}}</h2>
        <div class="card horizontal">
          <div class="card-image">
            <img src="/assets/{{imagen}}">
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <div class="card-panel blue-grey darken-1 white-text">{{descripcion}}</div>
              <dl>
                <dt>Precio:</dt>
                <dd>{{precio | currency}}</dd>
                <dt>Unidades Disponibles:</dt>
                <dd>{{stock}}</dd>
            </dl>
            </div>
            <div class="card-action">
              <button (click)="showCatalog()" class="btn grey lighten-5 black-text text-darken-2" type="button">Atrás</button>
            </div>
          </div>
        </div>
      </div>

    
  </div>
</div>
