// TiendaAngularReact/TiendaReactJS/components/Tienda.jsx
import React from 'react'; 
import { Redirect } from 'react-router-dom';
import update from 'immutability-helper'; //Manejo de arrays
import * as firebase from 'firebase';
import BarraNavegacion from './tienda/BarraNavegacion.jsx';
//import CatalogoRow from './tienda/CatalogoRow.jsx';
import Catalogo from './tienda/Catalogo.jsx';


class Tienda extends React.Component{


constructor(props) {
  super(props)
    this.state = {
      catalogo: [],
      productos: [],
      listaCarrito : [],
    }
    /*this.filtrarCatalogo = this.filtrarCatalogo.bind(this);
    this.actualizarDisponible = this.actualizarDisponible.bind(this)
    this.obtenerCantidad = this.obtenerCantidad.bind(this)*/
}



  render(){
    return(
     <p>test</p>
    )
  }

}

export default Tienda;

































/*
//==================Component Will Mount========================================
  componentWillMount(){
    if(this.state.catalogo == ""){                                                   //Verificar si se ha cargado previamente la información del catálogo
      alert('Inicializando Catalogo')
      const listaProductos = []                                                 //Arreglo temporal de objetos para almacenar todos los productos
      firebase.database().ref("productos").once("value").then((snapshot) => {
        snapshot.forEach(function(childSnapshot) {
            var key = childSnapshot.key;
            var childData = childSnapshot.val();
            listaProductos.push(childData);
        });
        this.setState({catalogo : listaProductos });
        this.setState({productos : this.state.catalogo});
      })
    }else{
      alert(this.state.catalogo)
    }
  }


//==============================================================================
  constructor(props) {
    super(props)
      this.state = {
        catalogo: [],
        productos: [],
        listaCarrito : [],
      }
      this.filtrarCatalogo = this.filtrarCatalogo.bind(this);
      this.actualizarDisponible = this.actualizarDisponible.bind(this)
      this.obtenerCantidad = this.obtenerCantidad.bind(this)
  }
//==============================================================================
      render(){
        return(
          <div className="tienda row">
            <div className="container">
            <BarraNavegacion contador={this.contadorCarrito()}/>
            <div className="left lista-productos box">
               <div className="row col s12 blue darken-1 animated fadeInDown fast">
                 <h4 className="col m6 s12 white-text left ">Cátalogo de productos</h4>
                 <h4 className="right col m6 s12 input-field">
                   <i className="material-icons prefix white-text">search</i>
                   <input onChange={this.filtrarCatalogo} type="text" id="descripcion" placeholder="aguacate"  type="text" className="white-text no-margin-bottom"/>
                   <label htmlFor="descripcion" className="white-text">¿Qué estás buscando?</label>
                 </h4>
               </div>
               {
                 this.mostrarProductos()
               }
             </div>

            </div>
          </div>
        )
  }

  mostrarProductos(){
    //console.log(this.state.productos)
    return this.state.productos.map(
              (producto) => { return <Catalogo key={ producto.id } id={producto.id}  nombre={ producto.nombre } imagen={ producto.imagen } descripcion={ producto.descripcion } disponible={ producto.disponible } precio ={producto.precio} actualizarDisponible={this.actualizarDisponible} obtenerCantidad={this.obtenerCantidad}/> }
            )
  }
  //============================================================================
  //                    Filtrar Productos
  //----------------------------------------------------------------------------
  filtrarCatalogo(event){
    this.state.productos = this.state.catalogo;                                 //Inicializar el catálogo de productos con la información de la base de datos
    let palabraFiltro = event.target.value.toLowerCase();                       //Pasar la infromación a minúsculas para hacerlas coincidir con el parámetro nombre en la base de datos
    let itemMatch = [];                                                         //Inicializar el arreglo de productos coincidentes

      for(let item of this.state.productos){                                    //Recorrer el arreglo de productos en el Catalogo
        let nombre = item.nombre.toLowerCase();                                 //crear una variable para comparar los productos
        if(nombre.includes( palabraFiltro )){                                   //Verificar que algún item del catálogo contenga los caracteres especificados en el campo de búsqueda
          itemMatch.push(item)}                                                 //Agregar el producto coincidente al arreglo
        }
      this.setState({productos : itemMatch});
      if(itemMatch.length == 0){
        this.state.productos = []
      }
      console.log(this.state.productos)
  }
 //=============================================================================
 //             Guardar Items en el carrito
 //--------------Actualizar Disponible------------------------------------------
    actualizarDisponible(item, cantidad, devolver:booleran = false){
      for (let productoLista of this.state.productos){
        if (productoLista.id == item.id){
          if(devolver == false){
            this.verificarCarrito(item, cantidad)
            productoLista.disponible = (Number(productoLista.disponible) - Number(cantidad))
          }
          else{
            productoLista.disponible = (Number(productoLista.disponible) + Number(cantidad))
          }
          this.setState({productos : this.state.productos})
          this.setState({listaCarrito : this.state.listaCarrito})
          console.log(this.state.listaCarrito)
        }
      }
    }

//-------------Verificar Carrito------------------------------------------------
  verificarCarrito(item, cantidad){
    if(this.guardarCarrito(item, cantidad) == false){                                     //Verificar que el item enviado como parámetro no exista previamente en el arreglo de objetos de productos
      this.state.listaCarrito.push(item)                                              //Si no existe agregarlo al arreglo
    }
    for(let item of this.state.listaCarrito){

    }
    this.setState({listaCarrito : this.state.listaCarrito})
    sessionStorage.setItem("Carrito", JSON.stringify(this.state.listaCarrito));        //Actualizar la sesion Carrito con los nuevos valores del arreglo en formato string
  }
//------------Agregar a Carrito-------------------------------------------------
guardarCarrito(item, cantidad){
  if(this.state.listaCarrito.length > 0){                                                     //Verificar que el carrito contenga informacion
    for(let itemGuardado of this.state.listaCarrito){                                        //Recorrer el arreglo de productos actuales en el carrito
      if(itemGuardado.id == item.id){                                                       //Verificar que el producto en el carrito coincida con el id del producto enviado como parámetro
        console.log(itemGuardado.descripcion +' Encontrado con: '+itemGuardado.cantidad + " Agregar: "+ cantidad)
        itemGuardado.cantidad = (Number(itemGuardado.cantidad) + Number(cantidad))
        return true //Devolver verdadero si el producto existia en el carrito
      }
    }
    return false; //Devolver falso si el producto no existia en el carrito
  }
  return false; //Devolver falso si el producto no existia en el carrito
}
//==============================================================================
//                    Verificar items en carrito
//---------------------Verificar carrito----------------------------------------
  checkCarrito(){
    for(let itemCarrito of this.state.listaCarrito){ //Recorrer el arreglo de productos almacenados en el carrito
      this.actualizarDisponible(itemCarrito.id, itemCarrito.cantidad) //Actualizar las cantidades de los productos a agregar en el carrito
    }
  }
//---------------------Verificar items en el carrito----------------------------
    itemsCarrito(){
      if(sessionStorage.getItem("Carrito")){                                    //Verificar si la sesión del carrito contiene información
        this.state.listaCarrito = JSON.parse(sessionStorage.getItem("Carrito")); //Actualizar la información del carrito con la sesión actual en formato JSON
        return JSON.parse(sessionStorage.getItem("Carrito"));                    //Devolver los items del carrito en formato JSON
      }
      return 0; //Devolver 0 si no existen carritos
    }
//--------------------Contador de items en menu---------------------------------
    contadorCarrito(){
      return this.itemsCarrito().length //Contar la cantidad de items en el carrito
    }
//--------------------Obtener Cantidad De Productos En Carrito------------------
  obtenerCantidad(id:number){
    for(let item of this.state.listaCarrito){ //Recorrer el arreglo de productos
      if(item.id == id){ //Comparar los id del producto en el arreglo con el id del producto enviado como parámetro
        return item.cantidad //Devolver la cantidad
      }
    }
    return null //Devolver vacio
  }
  componentDidMount(){
    console.log(this.state.productos)
    console.log('component Mounted')
    //console.log(sessionStorage.getItem("Carrito"))
    console.log(this.contadorCarrito())
  }
*/

//<Catalogo listado={this.state.productos} actualizarVistaDisponible={this.actualizarVistaDisponible.bind(this)}/>

// TiendaAngularReact/TiendaAngular2/src/app/components/tienda/tienda.component.ts
import {  Component, OnInit } from '@angular/core'; 
import { Router } from '@angular/router';
import { FormGroup, FormControl, Validators } from '@angular/forms'; //Importar los componentes ForModule, FormControl y Validator para manejar y validar los formularios
import { CurrencyPipe } from '@angular/common'
import { OnChanges } from '@angular/core';
import { ChangeDetectorRef } from '@angular/core';
//======================Importar Servicios======================================
import { AuthService } from "../../services/auth.service";
import { CarritoService} from '../../services/carrito.service';
import { TiendaService} from '../../services/tienda.service';
//======================Importar Modelos========================================
import { ProductoCarrito } from '../../models/ProductoCarrito';
import { Producto } from '../../models/Producto';
//=====================Importar Pipes===========================================
@Component({
  selector: 'tienda',
  templateUrl: './tienda.component.html',
  styleUrls: ['./tienda.component.css'],

})
export class TiendaComponent implements OnInit {

  private formulario : FormGroup; //Definir la variable formulario como un FormGroup
  private listaProductos : Producto[]; //Crear un objeto con la lista de tiendas obtenidos de la base de datos
  public productoCarrito : ProductoCarrito; //Definir un objeto con las pro
  private titulo : string;
  public session : string;

  constructor(private detectChanges:ChangeDetectorRef,  //Agergar el modelo ChangeDetectorRef para refrescar el renderizado de la página al existir algún cambio en vivo
              private router : Router, //Agergar el módulo Router para manejar las URL de la página
              private tiendaService : TiendaService, //Agergar el servicio TiendaService para interactuar con los items del catálogo de productos
              private auth : AuthService, //Agergar el servicio CarritoService para interactuar con los parámetros de sesión
              private carritoService : CarritoService //Agergar el servicio CarritoService para interactuar con los items del carrito
            ) { this.titulo = 'Catálogo de Productos' /*Definir el título de la página acual*/}


  ngOnInit() {
    if (!this.auth.checkSession()){ //Verificar si existe una sesión iniciada
      this.router.navigate(['/login']) //Si existe una sesión, navegar a la página de login
    }else{
    this.session = sessionStorage.getItem("Carrito") //Iniciar la sesión de Carrito verificando si existen productos en el mismo
      this.formulario = new FormGroup( //Iniciar las variables del formulario
        {
          'descripcion' : new FormControl(),
          'imagen': new FormControl(),
          'precio': new FormControl(),
          'cantidad': new FormControl(),
        }
      )
      this.mostrarProductos() //Ejecutar la función mostrar productos
    }
  }

//================Cargar Productos==============================================
  mostrarProductos(){
    if(!this.tiendaService.productosCatalogo){ //Verificar si se ha cargado previamente la información del catálogo
      this.tiendaService.getProductos().subscribe( //Ejecutar la consulta a la base de datos
        ()=>{
          this.listaProductos = this.tiendaService.catalogo; //inicializar la lista de productos con la información de la base de datos
          this.checkCarrito(); //Verificar si existen productos en el carrito
        }
      )
    }else{
          this.listaProductos = this.tiendaService.productosCatalogo; //Si se ha cargado previamente la información del catálogo, asignar la información actual
    }
  }
//================Agregar Productos=============================================
  agregarProducto(id:number, value:number){
    for (let item of this.tiendaService.productosCatalogo){ //Recorrer el catálogo de productos
      if(item.id == id){ //Verificar que el id del item actual corresponda con el item del catálogo
        if(item.disponible < value){//Si la disponibilidad es menor a la cantidad a añadir al carrito
          window.alert('Máxima existencia es: '+ item.disponible); //Mostrar un mensaje de alerta con la cantidad maxima disponible
        }else{
          let cantidadActual = item.disponible; //Crear una variable con la cantidad disponible en el catalogo
          //Convertir el objeto de la tienda en objeto carrito
          this.productoCarrito = {
            "id": item.id,
            "descripcion": item.descripcion,
            "imagen": item.imagen,
            "precio": item.precio,
            "cantidad": value //Asignar el valor enviádo como parámetro desde el campo de texto del producto
          }
          this.carritoService.verificarCarrito(this.productoCarrito); //Verificar si el producto se encuentra en el carrito
          item.disponible = cantidadActual - value; //Actualizar el valor del producto en el catalogo
        }
      }
    }
  }
  //================Filtrar Productos============================================
    filtrarCatalogo(filtro:string){
      this.listaProductos = this.tiendaService.filtrarProducto(filtro); //Actualizar el catálogo de productos mostrados de acuerdo al resultado obtenido en el filtro de productos
    }
  //================Actualizar Disponibles============================================
    checkCarrito(){
      for(let itemCarrito of this.carritoService.listaCarrito){ //Recorrer el arreglo de productos almacenados en el carrito
        this.tiendaService.actualizarDisponible(itemCarrito.id, itemCarrito.cantidad) //Actualizar las cantidades de los productos a agregar en el carrito
      }
    }
  //================Obtener Cantidad De Productos En Carrito======================
  obtenerCantidad(id:number){
    for(let item of this.carritoService.listaCarrito){ //Recorrer el arreglo de productos
      if(item.id == id){ //Comparar los id del producto en el arreglo con el id del producto enviado como parámetro
        return item.cantidad //Devolver la cantidad
      }
    }
    return null //Devolver vacio
  }
  //==============================================================================
}

<div class="tienda">
  <div class="container">
    <barra-superior></barra-superior>
    <!--lista-productos></lista-productos-->
    <div class="lista-productos col-xs-12 animated fadeInDownBig fast">
      <form [formGroup]="formulario" (onSubmit)="preventDefault(e)">
        <div class="col-sm-12">
          <h2 class="pull-left white-text">{{titulo}}</h2> 
          <span class="pull-right">
            <div class="form-group ">
              <label for="descripcion" class="white-text">¿Qué estas buscando?</label>
              <!-- Se utiiliza la etiqueta #filtro para identificar el input, se utliza el EventBiding onChange para pasar el valor del campo input a la funcion filtrarCatalogo-->
              <input formControlName="descripcion" type="text" id="descripcion" placeholder="aguacate" class="form-control input-filtro" (input)="filtrarCatalogo(filtro.value)" #filtro>
              <span class="error">Introduzca la información a buscar</span><!-- Mensaje de campo inválido-->
            </div>
          </span>
        </div>
      </form>
      <ul class="producto nav animated fadeInUpBig slow pull-left col-xs-12">
        <li class="col-md-3 col-sm-4 col-xs-12" *ngFor="let item of listaProductos" >
          <div class="box">
            <div class="img grayscale" [ngClass]="{grayscale:(item.disponible <= 0)}">
              <img src="{{item.imagen}}" alt="{{item.descripcion}}" class="img-responsive">
              <h4 class="text-center text-shadow">{{item.descripcion}}</h4>
            </div>
            <div class="informacion">
              <span class="badge carrito" *ngIf="this.obtenerCantidad(item.id)"><small class="white-text text-shadow"><i class="material-icons">shopping_cart</i> <p>{{this.obtenerCantidad(item.id)}}</p></small></span>
              <p><small><b>Precio: </b>{{item.precio | currency : 'USD' : 1-0-2 }}</small></p>
              <p><small><b>Disponibles: </b>{{item.disponible ? item.disponible : 'Agotado'}}</small></p>
              <div class="input-group" >
                <span class="input-group-btn">
                  <button class="btn btn-warning" type="button" [disabled]="(item.disponible <= 0)" (click)="agregarProducto(item.id, agregar.value)">Añadir</button>
                </span>
                <input type="number" [value]="1" [disabled]="(item.disponible <= 0)" min="0" max={{item.disponible}} class="form-control text-right" id="disponible"  #agregar>
              </div>
            </div>
            <div class="box footer">
              <a [routerLink]="['/tienda/detalle-producto/', item.id]" class="btn btn-secundary">Ver Detalle</a>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
