// tienda/Angular/src/app/barra-superior/barra-superior.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CatalogoComponent } from '../catalogo/catalogo.component';

@Component({
  selector: 'barra-superior',
  templateUrl: './barra-superior.component.html',
  styleUrls: ['./barra-superior.component.css']
})
export class BarraSuperiorComponent implements OnInit {
  private count: Number;

  @Input() catalogo: CatalogoComponent;
  showCart(){
    this.catalogo.showCart();
  }

  constructor() { }

  ngOnInit() {
    this.count = Number(0);
  }

  emptyCart(){
    alert("Carro de compras vacío. Agregue algunos productos primero.");
  }

  addCartCount(cantidad) {
    this.count = Number(this.count) + Number(cantidad);
  }

}

<nav class="white darken-1">
  <div class="nav-wrapper">
    <a [routerLink]="['']" class="brand-logo">La bodega</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a [routerLink]="['../store']"><i class="icon ion-md-apps"></i></a></li>
      <li *ngIf="count==0"><a (click)="emptyCart()"><i class="icon ion-md-cart"></i></a></li>
      <li *ngIf="count>0"><a (click)="showCart()"><i class="icon ion-md-cart left"></i>
        <span class="new badge" data-badge-caption="">{{count}}</span>
      </a></li>
      <li><a [routerLink]="['']"><i class="icon ion-md-filing"></i></a></li>
      <li><a [routerLink]="['/']"><i class="icon ion-md-exit"></i></a></li>
    </ul>
  </div>
</nav>

// tienda/React/src/components/BarraSuperior.js
import React from 'react';
import { Link } from 'react-router-dom';
import '../css/barra-superior.css';

class BarraSuperior extends React.Component{
  constructor(props){
      super(props);
      this.state = {
      }
  }

  emptyCart(){
    if (this.props.count === 0) {
      alert("Carro de compras vacío. Agregue algunos productos primero.");
    } else{
      this.props.showComponent("carro");
    }    
  }

  render(){
    return (
      <nav className="white darken-1">
        <div className="nav-wrapper">
          <Link to="/" className="brand-logo">La bodega</Link>
          <ul id="nav-mobile" className="right hide-on-med-and-down">
            <li><Link to='../store'><i className="icon ion-md-apps"></i></Link></li>
            <li><a href="#" onClick={this.emptyCart.bind(this)} className="cart-icon"><i className="icon ion-md-cart"></i>
              <span className="new badge cart-badge" data-badge-caption="">{this.props.count}</span>
            </a></li>
            <li><Link to='/'><i className="icon ion-md-filing"></i></Link></li>
            <li><Link to='/'><i className="icon ion-md-exit"></i></Link></li>
          </ul>
        </div>
      </nav>
    )
  }
}

export default BarraSuperior;
