// TiendaAngularReact/TiendaAngular2/src/app/components/login2/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms'; //Importar los componentes ForModule, FormControl y Validator para manejar y validar los formularios
import { AngularFire, FirebaseListObservable } from 'angularfire2';
import { Router } from '@angular/router';

import { AuthService } from "../../services/auth.service";

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  mensaje:string; //definir la variable error de tipo srting
  loginForm : FormGroup; //Definir la variable formulario como un FormGroup
  items: FirebaseListObservable<any[]>;
  email : string;
  password: string; 

  //===========================================================
  // Constructor
  //==========================================================

  constructor(private db: AngularFire, private auth : AuthService, private router: Router) {
    if(this.auth.checkSession()){
       this.router.navigate(['tienda'])
     }
  };


  //===========================================================
  // Métodos de inicialización
  //==========================================================

  ngOnInit() {
    this.email = "";
    this.password = "";
    if(this.auth.checkSession()){ //Verificar si existe una sesión iniciada
      this.router.navigate( ['/tienda'])
    }
    this.loginForm = new FormGroup(
      {
        'email' : new FormControl('', Validators.required),
        'password': new FormControl('', Validators.required),
      }
    )
  }

  checkLogin(){
    if(this.loginForm.valid){ /*Si el formulario se envía correctamente*/

      //================================================================================================================
      // Dar formato al email eliminando el caracter @ y . para que coincida con el valor alojado en la base de datos
      //================================================================================================================
      this.email = this.loginForm.value.email.toLowerCase().replace(/[^a-zA-Z 0-9.]+/g,'').replace(/\./g,'');
      this.password = this.loginForm.value.password; /*Asignar el valor password del formulario al valor password del objeto Usuario*/

      //================================================================================================================
      //  De acuerdo a   documentación de firebase2:
      //  Asignar la ruta usuarios seguido del email con su nuevo formato en la base de datos a consultar
      //================================================================================================================
      let loginUser = `/usuarios/${this.email}`
      const user = this.db.database.object(loginUser);
      user.subscribe(data => {
        if(data.$exists()){ //Verificar la existencia del usuario
          console.log ('Email correcto: ' + data.email)
          if (data.password == this.password){ //Si el usuario existe, verificar su contraseña
            this.mensaje = "Iniciando Sesión"; /*Mostrar mensaje en el formulario*/
            sessionStorage.setItem("Session", this.email); /*Definir el sessionStorage la llave "Session" con el valor del email validado*/
            console.log(this.mensaje); /*Mostrar mensaje en cónsola*/
            this.router.navigate(['tienda']); /*Redireccionar a la tienda*/
          }else{
            this.mensaje = 'Contraseña incorrecta'; /*Mostrar mensaje  de error  en formulario*/
            console.log(this.mensaje); /*Mostrar mensaje en cónsola*/
          }
        }else{
          this.mensaje = "El usuario" + this.loginForm.value.email + " no existe"; /*Mostrar mensaje de error en el formulario*/
          console.log(this.mensaje)
        }
      });
    }
  }

  /*checkLogin(){
  let loginUser = new Usuario; //Crear un objeto con las propiedades de Usuario
  if(this.loginForm.valid){ /*Si el formulario se envía correctamente
  loginUser.email = this.loginForm.value.email.toLowerCase(); /*Asignar el valor email del formulario al valor email del objeto Usuario*/
  /*  loginUser.password = this.loginForm.value.password; /*Asignar el valor password del formulario al valor password del objeto Usuario*/
  /*this.auth.getUsuarios().subscribe((data:Usuario[]) => {
  /*Recorrer el array de usuarios*/
  /*for( let i in data){
  /*Comparar que existe el email*/
  /*if (data[i].email == loginUser.email){
  console.log("Email: " +data[i].email+ " encontrado"); /*Mostrar mensaje en cónsola.*/
  /*Si el email coincide, Verificar la contraseña*/
  /*if (data[i].password == loginUser.password ){
  console.log("Iniciando sesión"); /*Mostrar mensaje en cónsola*/
  /*this.mensaje = "Iniciando Sesión"; /*Mostrar mensaje en el formulario*/
  /*sessionStorage.setItem("Session", loginUser.email); /*Definir el sessionStorage la llave "Session" con el valor del email validado*/
  /*this.router.navigate(['tienda']); /*Redireccionar a la tienda*/
  /*} else {
  /*console.log("Error de contraseña"); /*Mostrar mensaje en cónsola*/
  /*this.mensaje = 'Contraseña incorrecta'; /*Mostrar mensaje  de error  en formulario*/
  /*  }
} else {
this.mensaje = "El usuario" +loginUser.email+ " no existe"; /*Mostrar mensaje de error en el formulario*/
/*}
}
})
}
}*/


}

<div class="login"> 
  <div class="overlay">
  </div>
      <div class="col-md-6 col-sm-s12 form-container">
        <form [formGroup]="loginForm" (ngSubmit)="checkLogin()">
          <h4 class="text-center white-text">Inicia Sesión</h4>
          <div class="form-group ">
            <label for="email" class="white-text">Correo Electrónico</label>
            <input formControlName="email" type="email" id="email" placeholder="luis@email.com" class="form-control input-email" pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?">
            <span class="error">Formato de email inválido</span><!-- Mensaje de campo inválido-->
          </div>
          <div class="form-group">
            <label for="password" class="white-text">Contraseña</label>
            <input formControlName="password" type="password" id="password" placeholder="12345" class="form-control input-email" >
            <span class="error">Contraseña no puede ser vacía</span><!-- Mensaje de campo inválido-->
          </div>
          <div class="row text-center">
            <div class="mensaje"> <!--Mostrar el mensaje de error de inicio de sesión-->
              {{mensaje}}
            </div>
            <!--Deshabilitar el botón de enviar si los datos ingresados en el formulario son invá<lidos></lidos>-->
            <button type="submit" class="btn btn-success" [disabled]="!loginForm.valid" >Ingresar</button>
          </div>
        </form>

        <ul>
          <li class="text" *ngFor="let item of items | async">
            {{item.$value}}
          </li>
        </ul>

</div>

// TiendaAngularReact/TiendaReactJS/components/Login.jsx
import React from 'react';
import ReactDOM from 'react-dom'; 
import * as firebase from 'firebase';
import * as request from 'superagent';
import {  BrowserRouter as Router, Route, Link, Redirect } from 'react-router-dom'
//=========Importar Componentes=========================
import LoginFirebase from './FirebaseDB.jsx';
//========================================================

const USUARIODB = firebase.database().ref().child('usuarios')

class LoginForm extends React.Component{
  constructor(props) {
    super(props);
    this.state = { //Inicializar variables
      email: '',
      password: '',
      mensaje: '',
    };
    this.handleChange = this.handleChange.bind(this);
    this.checkLogin = this.checkLogin.bind(this);
  }
//================Verificar Sesión==============================================
  checkSession(){
    return sessionStorage.getItem("Session");
  }
//================Obtener Valor Inputs Formulario===============================
  handleChange(event) {
    if(event.target.id == "email"){ //Utilizar un eventListener para actualizar el valor de la variable email cuando este sea modificado
      this.setState({email: event.target.value});
    }
    if(event.target.id == "password"){ //Utilizar un eventListener para actualizar el valor de la variable password cuando este sea modificado
        this.setState({password: event.target.value});
    }
  }
//================Verificar Usuario=============================================
  checkLogin(event) {
    event.preventDefault(); //Prevenir que se envíe el formualrio

    let email = this.state.email.toLowerCase()
    let emailId = email.replace(/[^a-zA-Z 0-9.]+/g,'').replace(/\./g,''); //Dar formato al email eliminando el caracter "@" y "." para que coincida con el string en la base de datos
    let password = this.state.password; //Almacenar la contraseña en una variable
    let mensajeLogin = '';

    USUARIODB.child(emailId).once('value', function(snapshot) { //Consultar en la base de datos el valor del email enviado
    let userData = snapshot.val();
      if (userData !== null) { //Verificar que la respuesta del servidor no sea nula.
        //alert('user ' + email  + ' exists!' + snapshot.val());
        //console.log(snapshot.val())
        console.log ('Email correcto: ' + userData.email)
        if (userData.password == password){ //Si el usuario existe, verificar su contraseña
          mensajeLogin = "Iniciando Sesión"; //Mostrar mensaje en el formulario
          sessionStorage.setItem("Session", email); //Definir el sessionStorage la llave "Session" con el valor del email validado
        }else{
          mensajeLogin = 'Contraseña incorrecta'; //Mostrar mensaje  de error  en formulario
        }
      }else{
        mensajeLogin = "El usuario " +email + " no existe"; //Mostrar mensaje de error en el formulario
      }
    });
    this.setState({mensaje : mensajeLogin}); //Asignar el valor del mensaje y mostrarlo en pantalla
    console.log(mensajeLogin)
  }
//==============================================================================

//============Acciones Will mount===============================================

//============Acciones Renderizado==============================================
    render(){
    if (this.checkSession()){
      return <Redirect to='/tienda'/>
    }
      return(
        <div className="login row">
          <div className="col s6 form-container animated fadeIn slow">
            <form onSubmit={this.checkLogin}>
              <h4 className="text-center white-text">Inicia Sesión</h4>
              <div className="col s12 input-field">
                <input type="email" ref="email" id="email" value={this.state.email} onChange={this.handleChange} placeholder="luis@email.com" className="validate white-text" required aria-required="true" />
                <label htmlFor="email" data-error="Error en formato de email. Ejemplo: correo@email.com" data-success="Formato de email correcto">Correo Electrónico</label>
              </div>
              <div className="col s12 input-field">
                <input type="password" ref="password" id="password" value={this.state.password} onChange={this.handleChange} placeholder="12345" className="validate  white-text" required aria-required="true" />
                <label htmlFor="password" data-error="Contraseña no puede ser vacía" className="white-text">Contraseña</label>
              </div>
              <div className="col s12 center-align">
                <div className="mensaje">
                {this.state.mensaje}
                </div>
                <button type="submit" className="btn btn-success" >Ingresar</button>
              </div>
            </form>
          </div>
        </div>
     );
    }
//==============================================================================
}
export default LoginForm;
