// tienda/React/src/components/Carro.js
import React from 'react';
import axios from 'axios';
import '../css/carro.css';

class Carro extends React.Component{
    constructor(props){
        super(props);
        this.state = {
            show: true,
            items: this.props.items
        }

        this.itemsProcessed = []
        this.total = 0
    }

  componentDidMount(){
    let cart = this.props.itemsInCart

    for (var i in cart) {
        let word = cart[i].nombre;
        let unidades = cart[i].cantidad;
        let myItem = this.state.items.filter(c => c.nombre.toLowerCase() === word.toLowerCase());
        let subtotal = Number(myItem[0].precio) * Number(unidades);
        let precio = myItem[0].precio;
        let imagen = myItem[0].imagen;
        let json = {nombre: word, unidades: unidades,precio:precio, subtotal: subtotal, imagen: imagen};
        this.itemsProcessed.push(json);
        this.total = Number(this.total) + Number(subtotal)        
    }
  }

    pay(){
        for (var i in this.props.itemsInCart) {
            let index = this.getIndex(this.state.items, this.props.itemsInCart[i].nombre);
            let stock = Number(this.state.items[index].stock);
            this.updateStock(index, stock);
        }
        alert('Gracias por su compra.');
        this.hideCarro();
        this.props.cleanCatalog();
    }

    updateStock(index, stock){
        let url = 'https://tiendaphaetton.firebaseio.com/productos/'+index+'/.json';
        let body = '{"stock": '+stock+'}';
        axios.patch(url, body)
            .then(function (response) {
                console.log(response);
            })
            .catch(function (error) {
                console.log(error);
            });
    }


    listItems() {
        let items = this.itemsProcessed;
        return (
            <ul className="collection">
            {
            items.map((item) => {
                return (
                    <li className="collection-item avatar">
                        <img src={`../assets/${item.imagen}`} alt="" className="circle" />
                        <span className="title">{item.nombre}</span>
                        <p><strong>Unidades:</strong> {item.unidades}<br/>
                            <strong>Precio:</strong> ${item.precio}<br/>
                            <strong>Subtotal:</strong> ${item.subtotal}
                        </p>
                    </li>              
                );
            })
            }
        </ul>
        );
    }

    getIndex(allItems, name){
        for (var i in allItems){
        if (allItems[i].nombre === name){
            return i;
        }
        }
        return 0;
    }

    hideCarro() {
        this.setState({
            show: false
        });
        this.props.showComponent("catalogo");
    }

    render(){
        let content;       
        
        if(this.state.show){
            content=<div className="card white">
            <div className="card-content">
            <div className="row main">
                <div className="col m5">

                { this.listItems() }
                
                </div>
                <div className="col m7">
                    <div className="total">Total: ${this.total}</div>
                    <button onClick={this.hideCarro.bind(this)} className="btn white cart-button" type="button" name="mas">Cancelar</button>
                    <button onClick={this.pay.bind(this)} className="btn white cart-button" type="button" name="mas">Pagar</button>
                </div>
            </div>
            </div>
        </div>;
        }
        else {
            content=<div></div>;
        }

        return (
        <div>
            {content}
        </div>
        )
    }
}

export default Carro;

// tienda/Angular/src/app/carro/carro.component.ts
import { Component, Input } from '@angular/core';
import { CatalogoComponent } from '../catalogo/catalogo.component';
import { DataService } from '../data.service';

@Component({
  selector: 'carro',
  templateUrl: './carro.component.html',
  styleUrls: ['./carro.component.css']
})
export class CarroComponent {
  private show: boolean = false;
  private items: {nombre: string, unidades: Number, precio: Number, subtotal: Number, imagen: string}[] = [];
  private total: Number = 0;
  private allItems: any;
  private cart: any;

  @Input() catalogo: CatalogoComponent;
  showCatalog(){
    this.catalogo.showCatalog();
    this.hideCart();
  }

  showCart(cart, allItems){
    this.total = 0;
    this.items = [];
    this.allItems = allItems;
    this.cart = cart;
    for (var i in cart) {
      let word = cart[i].nombre;
      let unidades = cart[i].cantidad;
      let myItem = allItems.filter(c => c.nombre.toLowerCase() === word.toLowerCase());
      let subtotal = Number(myItem[0].precio) * Number(unidades);
      let precio = Number(myItem[0].precio);
      let imagen = myItem[0].imagen;
      let json = {nombre: word, unidades: unidades, precio: precio, subtotal: subtotal, imagen: imagen};
      this.items.push(json);
      this.total = Number(this.total) + Number(subtotal);
    }
    this.show = true;
  }

  pay(){
    for (var i in this.cart) {
      let index = this.getIndex(this.allItems, this.cart[i].nombre);
      let stock = Number(this.allItems[index].stock);
      this.dataService.updateStock(index, stock);
    }
    alert('Gracias por su compra.');
    window.location.reload();
  }

  getIndex(allItems, name){
    for (var i in allItems){
      if (allItems[i].nombre === name){
        return i;
      }
    }
    return 0;
  }

  hideCart(){
    this.show = false;
  }

  constructor(private dataService: DataService) { }
}

<div *ngIf="show" class="card white">
  <div class="card-content">
    <div class="row main">
      <div class="col m5">
        <ul class="collection">
          <li class="collection-item avatar" *ngFor="let item of items">
            <img src="/assets/{{item.imagen}}" alt="" class="circle">
            <span class="title">{{item.nombre}}</span>
            <p><strong>Unidades:</strong> {{item.unidades}}<br>
              <p><strong>Precio:</strong> {{item.precio | currency}}<br>
               <strong>Subtotal:</strong> {{item.subtotal | currency}}
            </p>
          </li>
        </ul>
      </div>
      <div class="col m7">
        <div class="total">Total: {{total|currency}}</div>
        <button (click)="showCatalog()" class="btn white cart-button" type="button" name="mas">Cancelar</button>
        <button (click)="pay()" class="btn white cart-button" type="button" name="mas">Pagar</button>
      </div>
    </div>
  </div>
</div>
