// TiendaAngularReact/TiendaAngular2/src/app/components/carrito/carrito.component.ts
import { Component, OnInit } from '@angular/core'; 
import { ChangeDetectorRef } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Router } from '@angular/router'; //Inyectar el componente router para manejar redirecciones URL
import 'rxjs/Rx';
//======================Importar Servicios======================================
import { AuthService } from "../../services/auth.service";
import { CarritoService } from '../../services/carrito.service';
import { TiendaService } from '../../services/tienda.service';
//======================Importar Modelos========================================
import { Producto } from '../../models/Producto';
import { ProductoCarrito } from '../../models/ProductoCarrito';
//==============================================================================

@Component({
  selector: 'carrito',
  templateUrl: './carrito.component.html',
  styleUrls: ['./carrito.component.css']
})
export class CarritoComponent implements OnInit {
  public listaCarrito : ProductoCarrito[] = []; //Crear un arreglo de productos para almacenar los productos guardados en el carrito
  public catalogo : Producto[] = []; //Crear un arreglo de productos para almacenar los productos guardados en el catalogo
  public titulo: string;

  constructor(private carritoService : CarritoService,
              private detectChanges:ChangeDetectorRef,
              private tiendaService : TiendaService,
              private auth : AuthService,
              private http : Http, private router : Router
            ) {
    this.titulo = 'Carrito de compras';
   }

  ngOnInit() {
    if (!this.auth.checkSession()){
      console.log(sessionStorage.getItem("Session"))
      this.router.navigate(['/login'])
    }else{
      this.listaCarrito = this.carritoService.itemsCarrito();
    }
  }

  //==============Calcular Totales================================================
    total(){
      let total :number = 0 //Inicializar los totales
      let items = this.carritoService.listaCarrito; //Iniciar la variable items con los items actuales en el carrito
      for(let subtotal of items ){ //recorrer los items dentro del carrito
       total += subtotal.cantidad * subtotal.precio; //Realizar el producto entre la cantidad y el precio y agregarlo al valor guardado anteriormente
      }
      return total; //Devolver el valor de la suma total de todos lso subtotales del producto
    }
  //=============Pagar Carrito==================================================
  pagarCarrito(){
    this.http.get('https://tienda-angular2.firebaseio.com/productos/.json') //Realizar una consulta a la base de datos
    .map((response : Response) => {
        this.catalogo =  response.json() //Asignar el valor obtenido en la consulta al arreglo de objetos catalogo
      }
    ).subscribe(
      ()=>{
        for (let itemCatalogo of this.catalogo){ //Recorrer el arreglo de productos obtenidos de la base de datos
          for (let item of this.listaCarrito){ //Recorrer el arreglo de productos en el carrito
            if ( itemCatalogo.id == item.id ){ //Comparar el id del producto del carrito con el id del producto almacenado en la base de datos
              let cantidad = Number(item.cantidad); //obtener la cantidad del producto actual en el carrito
              itemCatalogo.disponible = itemCatalogo.disponible - cantidad //Restar la disponibilidad del producto en la base de datos con la cantidad actual en el carrito
              this.actualizarDisponible(item.id, itemCatalogo).subscribe( //Ejecutar la funcion actualizarDisponibles enviando como parámetros el id y el objeto Producto en la base de datos
                (response) => {
                  this.vaciarCarrito() //Ejecutar la funcion vaciaCarrito
                }
              )
            }
          }
        }
        this.router.navigate(['/tienda']) //Redireccionar a la tienda
      }
    )
  }
  actualizarDisponible(id:number, itemCatalogo:Producto){
    return this.http.put(`https://tienda-angular2.firebaseio.com/productos/${id}.json`, itemCatalogo) //Ejecutar el método put a la url de la base de datos enviando como parámetro el objeto Producto con su nuevos valores disponibles
    .map((response : Response) => {
        return this.catalogo =  response.json() //Asignar a la lista de productos actuales el valor actualizado de los productos en la base de datos
      }
    )
  }
  //============Vaciar los items del carrito====================================
    vaciarCarrito(){
    sessionStorage.setItem('Carrito', '[]') //Asignar como parámetro un array vacío en formato string a la sesion Carrito
    this.listaCarrito = []; //Vaciar el arreglo de productos almacenados en el carrito
    this.carritoService.eliminarCarrito(this.listaCarrito); //Recorrer el arreglo de la lista almacenada en el servicio carritoService
    this.carritoService.listaCarrito = []; //Vaciar el arreglo en el servicio carritoService
    this.tiendaService.getProductos().subscribe() //Cargar de nuevo los productos desde la base de datos
    }
  //================Eliminar Productos Carrito==================================
    eliminarProducto(id:number, value:number){ //Obtener el id y valor de la cantidad de unidades del producto a eliminar
      for(let item of this.listaCarrito){ //recorrer el arreglo de productos almacenados en el carrito
        if(item.id == id){ //Verificar coincidencias entre el id del producto en el arreglo del carrito y el id recibido como parámetro
          let index = this.listaCarrito.indexOf(item); //Verificar la posición del producto actual en el arreglo de productos almacenados en el carrito
          if(value == null){ //Si no se envían cantidades del producto a eliminar (se elimina el ITEM juto a las cantidades del carrito)
            this.listaCarrito.splice(index, 1); //Eliminar el objeto Producto en la posición actual del item en el arreglo de objetos
            this.carritoService.eliminarCarrito(this.listaCarrito); //Actualizar la sesión de productos en el carrito
            this.total(); //Actualizar los totales en la vista carrito
            this.tiendaService.actualizarDisponible(id, Number(item.cantidad), true); //Ejecutar la función actualizar disponibles enviando como parámetros el id del producto, la cantidad y especificar que devolver el item es verdadero
          }else{
            if(value > 0){ //Si el valor es mayor que 0
               //Verificar que la cantidad indicada no sea mayor a la existente en el carrito
              let validar = (Number(item.cantidad) - value); //Crear una variable que almacene la resta de la cantidad actual con la cantidad recibida como parámetro a eliminar del carrito
              if(validar < 0){ //Si el resultado es menor a 0
                window.alert('La cantidad indicada excede a la cantidad en el carrito.'); //Ejecutar mensaje de alerta
              }else{
                item.cantidad = validar; //Asignar el valor de la resta obtenida en la propiedad cantidad del Objeto actual
                if (item.cantidad == 0) { //Verificar que se eliminen todos las unidades existentes en el carrito
                  //Si se eliminan las cantidades existentes en el carrito, eliminar el producto
                  this.listaCarrito.splice(index, 1);
                }
                //Asignar la nueva existencia al carrito
                this.carritoService.eliminarCarrito(this.listaCarrito); //Actualizar la información del arreglo de objetos de la sesion Carrito
                this.tiendaService.actualizarDisponible(id, Number(value), true); //Ejecutar la función actualizar disponibles enviando como parámetros el id del producto, la cantidad y especificar que devolver el item es verdadero
              }
            }else{
            window.alert('Debe especificar una cantidad válida'); //Mostrar mensaje de alerta si existe algún error
            }
          }
        }
      }this.detectChanges.detectChanges(); //Actualizar los cambios en la vista
    }
  //==============================================================================
}

<div class="tienda">
  <div class="container"> 
    <barra-superior></barra-superior>
    <div class="box carrito">
      <h2 class="titulo animated fadeIn slow" [ngStyle]="{display:inline-block}">{{titulo}}
      </h2>
      <div *ngIf="this.carritoService.contadorCarrito()">
        <ul class="producto list-group col-sm-6 col-xs-12 no-padding animated fadeIn slow">
          <li class="list-group-item flex col-xs-12 no-padding" *ngFor="let item of listaCarrito" [ngStyle]="{background:'#ededed'}">
            <div class="col-xs-12 no-padding">
              <div class="img img-flex no-padding pull-left">
                <a [routerLink]="['/tienda/detalle-producto/', item.id]"><img src="{{item.imagen}}" alt="{{item.descripcion}}" class="img-responsive no-padding"></a>
              </div>
              <div class="informacion">
                <span class="pull-right">
                  <i class="material-icons cursor" (click)="eliminarProducto(item.id, null)" >highlight_off</i>
                </span>
                <h5 class="text-left">{{item.descripcion}}</h5>
                <p><small><b>Precio: </b>{{item.precio | currency : 'USD' : 1-0-2 }}</small></p>
                <p><small><b>Cantidad: </b>{{item.cantidad}}</small></p>
                <div class="input-group">
                  <span class="input-group-btn">
                    <button class="btn btn-warning" type="button" (click)="eliminarProducto(item.id, eliminar.value)">Eliminar</button>
                  </span>
                  <input type="number" [value]="0" min="0" max={{item.cantidad}} class="form-control text-right" id="cantidad"  #eliminar>
                </div>
              </div>
              <div class="list-group-item footer">
                <div class="no-padding col-xs-6 text-right">
                  <h5><b>Subtotal: </b></h5>
                </div>
                <div class="no-padding col-xs-6 text-right">
                  <h5>{{this.carritoService.subtotal(item.precio, item.cantidad) | currency : 'USD' : 1-0-2}}</h5>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <div class="col-sm-6 col-xs-12 animated fadeIn slow">
          <div>
            <h2 class="text-right"><button class="btn btn-danger btn-sm"  type="button" (click)="this.vaciarCarrito()"><i class="material-icons"[ngStyle]="{'line-height' : '14px', 'font-size': '17px', 'position' : 'relative', 'top': '3px'}">delete</i> Vaciar Carrito</button></h2>
            <h2 class="text-right"> Total a pagar:</h2>
            <h3 class="text-right">{{ this.total() | currency : 'USD' : 1-0-2}}</h3>
            <p class="pull-right">
              <button class="btn btn-success " type="button"  (click)="pagarCarrito()"><i class="material-icons">credit_card</i> Pagar</button>
            </p>
          </div>
        </div>
      </div>
      <div *ngIf="!this.carritoService.contadorCarrito()">
        <p>No ha agregado productos al carrito de compras. Lo invitamos a dar un paseo por nuestra <a [routerLink]="['tienda']">Tienda Virtual</a></p>
      </div>
    </div>
  </div>

// TiendaAngularReact/TiendaReactJS/components/tienda/Carrito.jsx
import React from 'react';
import { Link, Redirect } from 'react-router-dom';
import * as request from 'superagent';
import { FormattedMessage } from 'react-intl';
import BarraNavegacion from './BarraNavegacion.jsx';
import CarritoDetalle from './CarritoDetalle.jsx' 

class Carrito extends React.Component{
  //===============================================================================
  //                    Constructor
  //------------------------------------------------------------------------------
  constructor(props) {
    super(props)
    this.state = {
      listaCarrito : [],
      inputValue:0,
      redirect : false,
      counter : 1,
      pagar : false
    }
    this.vaciarCarrito = this.vaciarCarrito.bind(this)
  }
  //==============================================================================
  //                    Component Will Mount
  //------------------------------------------------------------------------------
  componentWillMount(){
    this.setState({listaCarrito : JSON.parse(sessionStorage.getItem('Carrito')) ? JSON.parse(sessionStorage.getItem('Carrito')) : '[]' })
  }
  //============================================================================
  //                    Render
  //----------------------------------------------------------------------------
  render(){
    if(!sessionStorage.getItem('Session')){     //Verificar si existe sesión iniciada
      return <Redirect to="/" />
    }
    if(this.contadorCarrito()){
      return(
        <div className="tienda row">
          <div className="container">
            <BarraNavegacion contador={this.contadorCarrito()}/>
            <div className="animated fadeIn slow">
              <div className="box carrito">
                <div className="row col s12 blue darken-1 animated fadeInDown fast">
                  <h5 className="col m6 s12 white-text left ">Carrito de compras</h5>
                </div>
                <div className="col l8 m6 s12">
                  {
                    this.mostrarCarrito()
                  }
                </div>
                <div className="col l4 m6 s12">
                  <h5 className="right col s12 right-align"><button className="btn red darken-4 btn-sm"  type="button" onClick={this.vaciarCarrito}><i className="material-icons" style={{'lineHeight' : '14px', 'fontSize': '17px', 'position' : 'relative', 'top': '3px'}} >delete</i> Vaciar Carrito</button></h5>
                  <h5 className="right col s12 right-align"> Total a pagar:</h5>
                  <h5 className="right col s12 right-align animated pulse fast"> <FormattedMessage   id="total"  defaultMessage={`$ {total, number}`} values={{total : this.total()}}  /></h5>
                  <p className="right">
                    <button onClick={this.pagarCarrito.bind(this)} className="btn green darken-1" type="button"  ><i className="material-icons">credit_card</i> Pagar</button>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      )
    }else if(!this.contadorCarrito() && this.state.redirect == false){
      return (
        <div className="tienda row">
          <div className="container">
            <BarraNavegacion contador={this.contadorCarrito()}/>
            <div className="animated fadeIn slow">
              <div className="box white col s12 center-align" style={{padding: '5%'}}>
                <h5  style={{height : '70vh', display : 'table-cell', verticalAlign : 'middle'}} >No ha agregado productos al carrito de compras. Lo invitamos a dar un paseo por nuestra <Link to="/tienda">Tienda Virtual</Link></h5>
              </div>
            </div>
          </div>
        </div>
      )
    }else{
      return <Redirect to="/tienda"/>; //Redireccionar a la tienda
    }
  }
  //==============================================================================
  //                    Funciones
  //----------------------Mostrar items en carrito=-------------------------------
  mostrarCarrito(){
    return this.state.listaCarrito.map(
      (producto) => { return <CarritoDetalle key={ producto.id } id={producto.id}  descripcion={ producto.descripcion } imagen={ producto.imagen } descripcion={ producto.descripcion } cantidad={ producto.cantidad } precio ={producto.precio} actualizarDisponible={this.actualizarDisponible.bind(this)}/> }
    )
  }
  //==============================================================================
  //                    Verificar items en carrito
  itemsCarrito(){
    if(sessionStorage.getItem("Carrito")){                                    //Verificar si la sesión del carrito contiene información
      this.state.listaCarrito = JSON.parse(sessionStorage.getItem("Carrito")); //Actualizar la información del carrito con la sesión actual en formato JSON
      return JSON.parse(sessionStorage.getItem("Carrito"));                    //Devolver los items del carrito en formato JSON
    }
    return 0;                                                                  //Devolver 0 si no existen carritos
  }
  //--------------------Contador de items en menu---------------------------------
  contadorCarrito(){
    return this.itemsCarrito().length //Contar la cantidad de items en el carrito
  }
  //=============================================================================
  //             Guardar Items en el carrito
  //--------------Actualizar Disponible------------------------------------------
  actualizarDisponible(item:Object, cantidad:Number, remover:Boolean = false){
    for (let productoLista of this.state.listaCarrito){
      if (productoLista.id == item.id){
        productoLista.cantidad = cantidad
        if(productoLista.cantidad == 0 || remover == true){
          this.removerItem(item)
        }
      }
    }
    sessionStorage.setItem("Carrito", JSON.stringify(this.state.listaCarrito))
    this.setState({listaCarrito : this.state.listaCarrito})
  }
  //---------------Remover item del carrito--------------------------------------
  removerItem(item){
    let index = this.state.listaCarrito.findIndex(producto => producto.id === item.id)
    let newArray =   this.state.listaCarrito.splice(index, 1)
  }
  //-----------------Vaciar los items del carrito------------------------------------
  vaciarCarrito(){
    this.setState({listaCarrito : []})
    sessionStorage.setItem('Carrito', '[]') //Asignar como parámetro un array vacío en formato string a la sesion Carrito
  }
  //==============Calcular Totales================================================
  total(){
    let total :number = 0 //Inicializar los totales
    let items = this.state.listaCarrito; //Iniciar la variable items con los items actuales en el carrito
    for(let subtotal of items ){ //recorrer los items dentro del carrito
      total += subtotal.cantidad * subtotal.precio; //Realizar el producto entre la cantidad y el precio y agregarlo al valor guardado anteriormente
    }
    return total; //Devolver el valor de la suma total de todos lso subtotales del producto
  }
  //=============Pagar Carrito==================================================
  pagarCarrito(){
    const listaCarrito = this.state.listaCarrito                                   //Definir la constante lista carrito
    this.setState({ pagar : true})
    request
    .get('https://tienda-angular2.firebaseio.com/productos/.json')                //Realizar una consulta a la base de datos
    .then((res) => {
      if( res.error || !res.ok){                                                   //Si existe mensaje de error
        console.log('Se produjo un error al realizar la petición al servidor. '+error )
        alert('Se produjo un error al realizar la petición al servidor. '+error )
      }else{
        console.log('Conexión establecida. Actualizando base de datos')           //Mostrar mensaje en cónsola
        const respuesta = res.text                                                //Guardar la respuesta del servidor
        let catalogo = JSON.parse(respuesta)                                      //Convertir la respuesta del servidor en formato JSON
        for (let itemCatalogo of catalogo){                                       //Recorrer el arreglo de productos obtenidos de la base de datos
          for (let item of listaCarrito){                                         //Recorrer el arreglo de productos en el carrito
            if ( itemCatalogo.id == item.id ){                                    //Comparar el id del producto del carrito con el id del producto almacenado en la base de datos
              let cantidad = Number(item.cantidad);                               //obtener la cantidad del producto actual en el carrito
              itemCatalogo.disponible = itemCatalogo.disponible - cantidad;       //Restar la disponibilidad del producto en la base de datos con la cantidad actual en el carrito
              this.actualizarDB(itemCatalogo, cantidad)                           //Ejecutar la funcion actualizarDisponibles enviando como parámetros el id y el objeto Producto en la base de datos
            }
          }
        }
      }
    }
  )
}

actualizarDB(itemCatalogo, cantidad){
  request.put(`https://tienda-angular2.firebaseio.com/productos/${itemCatalogo.id}.json`)  //Realizar consulta a base de datos
  .set('Content-Type', 'application/json')                                                 //Especificar el tipo de datos
  .send(itemCatalogo)                                                                      //Enviar el producto como parámetro
  .then((res) => {                                                                         //Manejar la respuesta del servidor
    if( res.error || !res.ok){                                                             //Si ocurre un erro
      console.log('Se produjo un error al actualizar la base de datos. '+error );
      alert('Se produjo un error al actualizar la base de datos. '+error)                  //Mostrar alerta
    }else{
      if(this.state.listaCarrito.length == 1){                                             //Si la cantidad de items en el carrito es 1, vaciar el carrito y actualizar la variable redirect a true
        this.vaciarCarrito()
        this.setState({ redirect : true })
      }else{
        let counter = (Number(this.state.counter) + 1)                                     //Si no, Crear una variable contador
        if(counter == this.state.listaCarrito.length){                                     //Cuando la variable contador sea igual al número de productos en el carrito (se haya recorrido el arreglo)
          this.vaciarCarrito()                                                               //Vaciar carrito
          this.setState({ counter : counter})                                                //Actualizar el estado de la variable contador por el contador actual
          this.setState({ redirect : true })                                                 //Cambiar el estado de redireccion a true
        }else{
          this.setState({ counter : counter})                                              //Actualizar el estado de la variable contador por el contador actual
        }
      }
    }
  })
}

  componentDidUpdate(){
    console.log('Actualización de disponibilidad correcta.');                               //Mostrar mensaje en consola cada vez que el producto sea actualizado en la base de datos
  }
}

export default Carrito;
